[package]
name = "wol-web-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde = "1"
serde_json = "1"
eui48 = "1.1.0"
askama = "0.11"
toml = "0.5"
